### ISSUE TITLE
Use of Kernel#open is a security risk - how can I improve it?

### ISSUE THREAD

**Issue by Whatapalaver** [Whatapalaver/jsonl-parsing-cli#3]

**Comment by smowafy** [comment]
Is there a problem with using `File.open` with append mode? I see you used `File.open` already to create the output file so why not use it there too?
Please tell me if I'm missing something though

**Comment by Whatapalaver** [comment]
Thanks @smowafy - you are right. It's all covered in the rubocop manual.....

**Comment by smowafy** [comment]
I can do this quick fix if possible of course

**Comment by Whatapalaver** [comment]
I’d be happy to take your PR for this.
